# Generated by Django 2.1.5 on 2019-03-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.Candidate')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.OfficeModel')),
            ],
        ),
    ]
