# Generated by Django 2.1.5 on 2019-04-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_voteresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteresult',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='voteresult',
            name='office',
        ),
        migrations.RenameField(
            model_name='officemodel',
            old_name='office_type',
            new_name='type',
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
    ]
